name: Render build deploy

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install R packages
        run: |
          install.packages(c("knitr", "rmarkdown", "quarto", "stringr"))
        shell: Rscript {0}
        
      - name: Render PDF
        run: |
          quarto::quarto_render("doc.qmd")
        shell: Rscript {0}
        
      - name: Push to branch
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: full-pdf
          folder: .
          commit-message: "Render PDF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}