name: Render build deploy

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@main
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install R packages
        run: |
          install.packages(c("knitr", "rmarkdown", "quarto", "stringr"))
        shell: Rscript {0}
        
      - name: Render PDF
        run: |
          quarto::quarto_render("doc.qmd")
        shell: Rscript {0}
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout full-pdf
          git add doc.pdf
          git commit -m "Render PDF"
          git push
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}