name: Reopen Issue

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month

jobs:
  reopen-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Reopen Issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              state: 'open'
            });
                  
      - name: Add Comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              body: '🔄 This issue has been automatically reopened by GitHub Actions.'
            });